export const REQUEST_USER_PROFILE_START = "REQUEST_USER_PROFILE_START";
export const REQUEST_USER_PROFILE_SUCCESS = "REQUEST_USER_PROFILE_SUCCESS";
export const REQUEST_USER_PROFILE_ERROR = "REQUEST_USER_PROFILE_ERROR";

